about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "<str:username>/follow/", views.profile_follow, name="profile_follow"
    ),
    path("new/", views.new_post, name="new_post"),
    path(
        "<str:username>/<int:post_id>/edit/",
        views.post_edit,
        name="post_edit"
    ),
    path("<str:username>/<int:post_id>/", views.post_view, name="post"),
    path("<str:username>/", views.profile, name="profile"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path(
        "<username>/<int:post_id>/comment/",
        views.add_comment,
        name="add_comment"
    ),
    path(
        "<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/urls.py
from django.contrib import admin
from django.conf.urls import handler404, handler500
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("", include("posts.urls")),
]

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        "Заголовок",
        max_length=200,
        help_text="Дайте подробное описание группе"
    )
    slug = models.SlugField(
        "Слаг",
        max_length=100,
        unique=True,
        blank=True,
        help_text=("Укажите адрес для страницы группы. Используйте только "
                   "латиницу, цифры, дефисы и знаки подчёркивания"),
    )
    description = models.TextField(
        "Текст",
        help_text="Опишите суть группы",
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        "Текст",
        help_text="Дайте короткое описание поста"
    )
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts")
    group = models.ForeignKey(
        Group,
        verbose_name="Choose a group",
        help_text="Select a group from existing",
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True)
    image = models.ImageField(upload_to="posts/", blank=True, null=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name="comments",
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments")
    text = models.TextField(
        "Комментарий",
        help_text="Напишите комментарий"
    )
    created = models.DateTimeField("date created", auto_now_add=True)

    class Meta:
        ordering = ["created"]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following")

posts/forms.py
from django.contrib.auth import get_user_model
from django.forms import ModelForm, Textarea
from .models import Comment

from .models import Post

User = get_user_model()


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", "image"]
        labels = {
            "text": "Напишите о чем Ваш пост: ",
            "group": "Выберите группу: ",
        }

        widgets = {
            "text": Textarea(attrs={
                "class": "form-contol",
                "placeholder": "Новый пост"
            })
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, Follow
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from yatube.settings import PAGINATOR


User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        {'page': page, }
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'group.html', {'page': page, 'group': group, })


@login_required
def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return redirect('index')
        return render(request, 'new.html', {'form': form})
    form = PostForm()
    return render(request, 'new.html', {'form': form})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user_posts = author.posts.all()
    paginator = Paginator(user_posts, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    following = request.user.is_authenticated and Follow.objects.filter(
        author=author, user=request.user
    ).exists()
    context = {
        'page': page,
        'author': author,
        'user_posts': user_posts,
        'following': following,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'author': post.author,
        'comments': comments,
        'form': form,
    }
    return render(request, 'post_view.html', context)


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)

    if post.author != request.user:
        return redirect('post', username, post_id)

    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )

    if form.is_valid():
        post.save()
        return redirect('post', username, post_id)

    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'new.html', context)


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        form.save()
        return redirect('post', username=username, post_id=post_id)
    return render(request, 'comments.html', {'form': form, 'post': post})


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'post_list': post_list}
    return render(request, 'follow.html', context)


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    if request.user == author:
        return redirect('profile', username)
    if not Follow.objects.filter(user=request.user, author=author).exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('profile', username)


@login_required
def profile_unfollow(request, username):
    unfollow_user = get_object_or_404(User, username=username)
    get_object_or_404(
        Follow,
        user=request.user,
        author=unfollow_user
    ).delete()
    return redirect('profile', username=username)

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
        <h1>{% block header %}{% endblock %}</h1>
            {% block content %}
                <!-- Содержимое страницы -->
            {% endblock content %}
            </div>
    </main>
        {% include 'footer.html' %}
</body>
</html>

templates/follow.html
{% extends "base.html" %} 
{% block title %} Latest author updates {% endblock %}

{% block content %}
<div class="container">

    {% include "includes/menu.html" with follow=True %}

        <h1>Latest author updates </h1>

        {% for post in page %}
            {% include "includes/post_item.html" with post=post %}
        {% endfor %}

        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with items=page paginator=paginator %}
        {% endif %}

    </div>
{% endblock %}

templates/footer.html
<!-- Шаблон footer.html -->
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">About Author</a>
    <a href="{% url 'about:tech' %}">About Technology</a>
  </p>
  <p class="m-0 text-dark text-center ">Social network <span style="color:red">Ya</span>tube © {{ year }}, all rights reserved..</p>
</footer>

templates/group.html
{% extends "base.html" %}

{% block title %} Community posts {{ group.title }} {% endblock %}
{% block header %} {{ group.title }} {% endblock %}

{% block content %}
{% load user_filters %}

      <p>{{ group.description }}</p> 

      {% for post in page %}
          <div class="card mb-3 mt-1 shadow-sm">
          {% load thumbnail %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text|linebreaksbr }}</p>
          <h6>Автор: {{ post.author.get_full_name }}, Publishing date: {{ post.pub_date|date:"d M Y"}}</h6>
          </div>
      {% endfor %}
      {% include "includes/paginator.html" %}
 {% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %} Latest updates {% endblock %}
{% load thumbnail %}
{% block content %}
<div class="container">

    {% include "includes/menu.html" with index=True %}

    <h1>Latest updates on site</h1>
    {% load cache %}
    {% cache 20 index_page %}
    {% for post in page %}
    {% include "includes/post_item.html" with post=post %}
    {% endfor %}
    {% endcache %}
    {% if page.has_other_pages %}
    {% include "includes/paginator.html" with items=page paginator=paginator %}
    {% endif %}

</div>
{% endblock %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        User: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new_post' %}">New Post</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Change Password</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </nav>
</nav>

templates/new.html
{% extends "base.html" %} 
{% block title %}Create a new post{% endblock %} 
{% block header %} {% if post is None %}Create a new post{% else %}Редактировать пост{% endif %} {% endblock %} 
{% block content %} 
{% load user_filters %}
{% load static %}
    <div class="features"> 
        {% for error in form.errors %}       
            <div class="alert alert-danger" role="alert">
                {{ error|escape }}
            </div>
        {% endfor %}
        <form method="post" enctype="multipart/form-data" action={% if post is None %} "{% url 'new_post' %}" {% else %} "{% url 'post_edit' post.author.get_username post.id%}" {% endif %}>
        {% csrf_token %}
        {% for field in form %}
             <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                 <div class="col-md-6">                    
                    {{ field|addclass:"form-control" }}
                    {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                    {% endif %}
                   </div>                
                 </div>
         {% endfor %}
        
                <div class="col-md-6 offset-md-4">           
                    <button type="submit" class="btn btn-primary">
                        {% if post is None %} Добавить запись {% else %} Редактировать {% endif %} 
                    </button>
                </div>
          
        </form> 
     </div> 
{% endblock %} 

templates/post_view.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}
<main role="main" class="container">
        <div class="row">
            {% include "includes/author_card.html" with author=author %}      
            <div class="col-md-9"> 
                {% include "includes/post_item.html" with post=post %}
                {% include "includes/comments.html" with comment=post.comment.all %}      
            </div>
        </div>
</main>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}{{author.username}}{% endblock %}
{% block header %}User profile {{author.username}}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<main role="main" class="container">
    <div class="row">
        {% include "includes/author_card.html" with author=author following=following profile=True %}
        <div class="col-md-9">
            {% for post in page %}
                {% include "includes/post_item.html" with post=post %}      
            {% endfor %}
            {% include "includes/paginator.html" %}
        </div>
    </div>
</main>
{% endblock %}